version: '3.9'

services:
  api-dev:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    command: yarn start:debug 0.0.0.0:9229
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 3001:3001
      - 9229:9229
      - 5555:5555
    depends_on:
      - mongo
      - redis
    networks:
      - fit-finances-api

  api-prod:
    build:
      dockerfile: Dockerfile
      context: .
      target: production
    env_file:
      - .env
    ports:
      - 3001:3001
    depends_on:
      - mongo
      - redis
    networks:
      - fit-finances-api

  redis:
    image: redis:7
    command: redis-server --requirepass redis
    ports:
      - 6379:6379
    networks:
      - fit-finances-api

  mongo:
    build: ./docker/mongodb_replica
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_REPLICA_HOST: host.docker.internal
      MONGO_REPLICA_PORT: 27017
    volumes:
      - ./.docker/mongo:/data/db
    ports:
      - 27017:27017
    networks:
      - fit-finances-api

networks:
  fit-finances-api:
    driver: bridge
